### ISSUE TITLE
XML Parser broken

### ISSUE THREAD

**Issue by mitchross** [sammychl/angular-xml2json#7]
angular.js:12783 TypeError: xmlcode.replace is not a function
    at Object.xml2json.parser (angular-xml2json.js:37)

Connecting to https://itunes.apple.com/rss/customerreviews/id=324684580/sortBy=mostRecent/xml

**Comment by dremy** [comment]
This is because what you're loading is not a string. I will submit a pull request with a string validation first.

`if (typeof xmlcode !== 'string') {
            // xmlcode = xmlcode.toString();
            return console.log('Make a string first.', xmlcode);
        }`
